server:
  port: 8000

web:
  resolverPrefix: /WEB-INF/
  resolverSuffix: .jsp
  resourceHandler: /resources/**
  resourceLocation: /resources/

logging:
  file: logs/sample.log
  pattern:
    console: "[%d{yyyy-MMM-dd HH:mm:ss:sss}] %clr([%p]) %clr([%t]){magenta} [%c] %clr([%m]){blue}%n"
    file: "[%d{yyyy-MMM-dd HH:mm:ss:sss}] [%p] [%t] [%c] [%m]%n"
